---

name: Release Git-Utils

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - run: go test
      - run: go build
