---

name: Release Git-Utils

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build: 
    name: GoReleaser builds
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        sid: go